### ISSUE TITLE
Fix relative urls to work with github.io deployment

### ISSUE THREAD

**Issue by vvasuki** [vedavaapi/ullekhanam-ui-v1#1]
Relative urls like ../assets/images/booklist.jpg break when built and deployed on github pages. Instead please drop the initial ../, as shown in https://github.com/vedavaapi/ullekhanam-ui-v1/commit/9e346a53f7f83d58316385ae7308b1395b447a62 . That will ensure all of the below:
- relative urls are resolved relative to the base url provided while building (blank by default)
- The page can be served from https://vedavaapi.github.io/ullekhanam-ui-v1/
- ng serve will continue to work

While at it, it would be good to include the below dependency:
`"angular-cli-ghpages": "git+https://github.com/angular-schule/angular-cli-ghpages.git",` , as shown in the same cl.

Further, please update the README as shown in https://github.com/vedavaapi/ullekhanam-ui-v1/commit/0ac03492f74d05d58d55778cd46b48d3882f8e72 .

**Comment by manikanta29788** [comment]
Fixed
