### ISSUE TITLE
Deleting Image annotation / Text annotation

### ISSUE THREAD

**Issue by manikanta29788** [vedavaapi/ullekhanam-ui-v1#3]
Hi Vishwas,

Will the user have option for deleting the image annotation / text annotation, if so do give an brief explanation on how to delete the image annotation / text annotation.

**Comment by manikanta29788** [comment]
Sorry there is an API already exist for deleting the entity, can you explain how it works for Image / Text annotation.

**Comment by vvasuki** [comment]
Any image or text annotation is an entity - just supply what ever you would supply to the post API. Most important is the content._id field in each of the input JsonNodeObjects.
