### ISSUE TITLE
Fix bad filename

### ISSUE THREAD

**Issue by vvasuki** [vedavaapi/ullekhanam-ui-v1#6]
Copying over from https://github.com/vedavaapi/ullekhanam-ui/issues/2 :

> Thanks for the tip - based on that I have an alternate fix which will avoid this extra step. Just change the bad file reference in .angular-cli.json as done in 2c1a5ec#diff-c970ed04bf59daa7f18d995cd0e73c9a . Could you replicate this change in your codebase similarly so that this change wont be overwritten with future updates?
> 
> The principle is that we should not need to update automatically generated files.

**Comment by manikanta29788** [comment]
Fixed and code pushed
